### PR TITLE
Update npm dependencies

### PR DESCRIPTION
**Pull request by nodeg**
This PR updates the npm dependencies to their latest version. Typescript, however, has to remain on a version < 4.2 because `@angular/compiler-cli` depends on it.
I haven't tested the changes. Hopefully the CI will show some meaningful results.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
I would rather prefer if we could close this and use https://dependabot.com/javascript/ instead. That would automate your PR for the future and we don't have to think about it.

**Review by SchoolGuy — APPROVED** [review]
Even though we don't have dependabot configured, I would merge this...

**Comment by nodeg** [comment]
I totally forgot dependabot. Sure, it makes sense to use it for future updating.

**Comment by SchoolGuy** [comment]
I am hesitating to merge because the pipeline is stuck. Either you retrigger it or I do it tomorrow from the PC but something is not right... Either on GitHub or on our side...

**Comment by nodeg** [comment]
Jep. Some earlier jobs are queued, too. Let's wait until tomorrow. See https://www.githubstatus.com/incidents/s654n76c1bwr

**Comment by nodeg** [comment]
Today the CI looks better.

**Comment by SchoolGuy** [comment]
Actually it doesn't the Linters AND the Tests are completely missing. But anyway we will merge. Maybe because the Jobs didn't get created in the first place...

**Pull request merged**
