### PR TITLE
[WIP] mockup overview page

### PR DESCRIPTION
**Pull request by bowlerct**
Mockup overview page to get us thinking about layout. It will be easier to write the code if we know what the pages should look like and the flow between them. Some things included are

* Page hooks for installers to add their own brandings, etc. into page header and footer
* Responsive menus to allow management from mobile devices

### Screenshots
overview_configurations

overview_resources

overview_actions

overview_profile

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@bowlerct I don't know why but I missed your PR! I am on the works with @nelliesnoodles on the initial version. After that we can think again how we do want to layout our new Webinterface. Many thanks on the Mock still! I think it will guide us after the inital work is done. It will be made public in March.

**Comment by SchoolGuy** [comment]
@bowlerct Feel free to rebase and comment on our current work. Create Issues or give other comments! If you desire to work more on this repository, I would invite you to our Web Development team! Nellie and I are both Angular beginners, so you probably will have a lot to say... XD

**Comment by bowlerct** [comment]
@SchoolGuy I would like to continue working on this. Give a few days to rebase and look over what you two have done. I'm new to angular as well.

**Comment by bowlerct** [comment]
@SchoolGuy I'm trying to figure out the angular workflow. There are two projects, cobbler-api and cobbler-frontend. The actual cobbler api will done with python in the cobbler repo correct? So is the cobbler-api angular project supposed to be a mock service for it?

**Comment by SchoolGuy** [comment]
@bowlerct We have three projects:

- Typescript-XMLRPC: Typescript XMLRPC Library which is generic.
- Cobbler-API: Library in Typescript which will utilize above Library to call the real Cobbler API.
- Cobbler-Frontend: UI Code to visualize our data.

I will write docs tomorrow to clarify it and describe how to do a development setup (wanted to do that initially last Sunday...).

**Comment by SchoolGuy** [comment]
@bowlerct Since I didn't have time yesterday I have created an issue to track my progress with the docs. When I am done with a PR for that issue you may test the new instructions and review them: https://github.com/cobbler/cobbler-web/issues/10

**Comment by bowlerct** [comment]
Thanks. I see how it’s fitting together now. There’s a lot of changes so I’m going to start fresh. Will work on pulling out all the mock data into a mock data proxy service so we’re not cluttering the code.

**Pull request closed without merging**
