### PR TITLE
Change component selector prefix from 'app' to 'cobbler'

### LINKED ISSUE #91: Add custom cobbler prefix to components
**Is your feature request related to a problem? Please describe.**

Currently we use the default `app-` prefix for components. Let's use a custom prefix that suits our project more.

**Describe the solution you'd like**

Use the custom `cobbler-` prefix for all components as it shows that the components is belonging to the Cobbler project.

**Describe alternatives you've considered**

None

**Additional context**

See https://blogkashif.medium.com/change-prefix-of-component-in-angular-application-34c8d8a86dbf how to do it.

### PR DESCRIPTION
**Pull request by jsowers13**
Fixes #91

### CODE REVIEW

**Review by SchoolGuy — CHANGES_REQUESTED** [review]
To do this change we need to change the existing components prefixes as well. The two files touched are a very good step already!

**Comment by SchoolGuy** [comment]
@jsowers13 I pushed some fixes to the `main` branch. Before you continue with this you may want to rebase your branch onto `main`.

**Comment by jsowers13** [comment]
I edited the prefix of all the <componentname>.component.ts files in the project/cobbler-frontend/src

I did note on a couple of the files that this import seems to be causing a problem:

import {CobblerApiService, COBBLER_URL} from 'cobbler-api';

**Review by SchoolGuy — CHANGES_REQUESTED** [review]
So the linter now tells me that you sadly missed one component per file I list below:

- `app.component.spec.ts`
- `login.component.spec.ts`
- `manage-menu.component.spec.ts`
- `settings-edit.component.spec.ts`

Those specfiles do contain mock components so we don't accidentally test the dependencies as well in the Unit Tests.

**Comment by jsowers13** [comment]
i updated the missing components with the new prefix. Sorry for the missed spec components

**Comment by SchoolGuy** [comment]
@jsowers13 Thanks a lot. At the moment GitHub Actions are degraded, meaning I will wait a bit before I can review and tell you more about the state of this PR.

If you feel motivated I would appreciate if you could rebase the PR so we get rid of that merge commit you did and squash the commits into a single one that is optimally signed. If not that is not a problem though.

**Comment by SchoolGuy** [comment]
Sorry it seems I tabbed not far enough. I did not mean to close the PR.

Edit: It seems the shortcut got messed up. Anyway.... :D

**Comment by jsowers13** [comment]
Im not sure how to rebase a PR? Id be happy to do it if you could explain
the process to me

**Comment by SchoolGuy** [comment]
@jsowers13 Here is a tutorial that is a bit dated but it should still apply. - https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request

Edit: Since you use gitpod apparently it is hard to sign the commits. But it is not a hard requirement as previously said.

**Comment by SchoolGuy** [comment]
@jsowers13 Since GH Actions are now working again: The unit tests show that you forgot two more places:

- `app.component.html`
- `settings-edit.component.html`

The HTML selectors are not yet correctly adjusted.

**Comment by jsowers13** [comment]
I changed those components in the html files

**Review by SchoolGuy — APPROVED** [review]
Thank you for this contribution!

**Comment by SchoolGuy** [comment]
I took the liberty of squashing the commits, polishing the commit message and rebasing the PR. Once the CI is done I will merge the PR. :)

**Pull request merged**
